### ISSUE TITLE
EventDispatcher not found

### ISSUE THREAD

**Issue by primerg** [rafrsr/generic-api#1]
Getting this error using the SampleAPI.php

Fatal error: Class 'Symfony\Component\EventDispatcher\EventDispatcher' not found in /path..i/vendor/rafrsr/generic-api/src/GenericApi.php on line 61

So I added "symfony/event-dispatcher" : "~2.8" in composer.json

After adding that, I'm getting the following error:

Fatal error: Call to a member function dispatch() on null in /path../vendor/rafrsr/generic-api/src/GenericApi.php on line 139

**Comment by rafrsr** [comment]
@primerg thanks for your comment.

> Fatal error: Class 'Symfony\Component\EventDispatcher\EventDispatcher' not found in /path..i/vendor/rafrsr/generic-api/src/GenericApi.php on line 61

fixed on commit, c51319a (added 'symfony/event-dispatcher' dependency 👍 )

In the other hand the event dispacther is initialized in the GenericApi constructor.

You are using the SampleAPI as is? see the `tests` folder. Otherwise if you are overriding the SampleAPI must call `parent::__construct()`

The following APIs use this library and can serves as a guide:

https://github.com/ynloultratech/pepaynation-api
https://github.com/ynloultratech/qpay-api

any  other question or issue it will be a pleasure to assist you.
